import type { CountryProfile } from "@/lib/countries/types";
import { americanTaxEngine } from "./tax-engine";
import { americanVehicles } from "./vehicles";
import { americanGovernmentRetirement } from "./government-retirement";
import { americanTaxCredits } from "./tax-credits";
import { usaProfiles } from "./sample-profiles";
import { americanInsights } from "./insights";
import { americanRmd } from "./rmd";
import { americanBenchmarks } from "./benchmarks";
import { americanFlowchartSteps } from "./flowchart-steps";

export const USA: CountryProfile = {
  code: "US",
  displayName: "United States",
  shortLabel: "USA",
  flagEmoji: "🇺🇸",
  homeCurrency: "USD",
  locale: "en-US",
  jurisdictions: [
    { code: "AL", name: "Alabama" },
    { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" },
    { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },
    { code: "DE", name: "Delaware" },
    { code: "DC", name: "District of Columbia" },
    { code: "FL", name: "Florida" },
    { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" },
    { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" },
    { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" },
    { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" },
    { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" },
    { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" },
    { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" },
    { code: "WY", name: "Wyoming" },
  ],
  defaultJurisdiction: "CA",
  filingStatuses: [
    { value: "single", label: "Single" },
    { value: "married-jointly", label: "Married Filing Jointly" },
    { value: "married-separately", label: "Married Filing Separately" },
    { value: "head-of-household", label: "Head of Household" },
  ],
  defaultFilingStatus: "single",
  taxYearLabel: (year) => String(year),
  taxYearBoundary: { startMonth: 1, startDay: 1 },
  taxEngine: americanTaxEngine,
  vehicles: americanVehicles,
  governmentRetirement: americanGovernmentRetirement,
  taxCredits: americanTaxCredits,
  profiles: usaProfiles,
  insights: americanInsights,
  rmd: americanRmd,
  benchmarks: americanBenchmarks,
  flowchartSteps: americanFlowchartSteps,
  wizardRegisteredCategories: ["Roth IRA", "401k"],
  flowchartWiki: {
    tipName: "r/personalfinance",
    linkText: "r/personalfinance",
    linkUrl: "https://www.reddit.com/r/personalfinance/wiki/commontopics",
  },
  regionTaxLabel: "State",
};
