/**
 * Static map of ticker symbols to company/fund names.
 * Includes S&P 500 companies, popular ETFs, and Canadian tickers.
 */

const TICKER_NAMES: Record<string, string> = {
  // === S&P 500 Companies (alphabetical by ticker) ===
  A: "Agilent Technologies",
  AAL: "American Airlines",
  AAPL: "Apple",
  ABBV: "AbbVie",
  ABNB: "Airbnb",
  ABT: "Abbott Laboratories",
  ACGL: "Arch Capital Group",
  ACN: "Accenture",
  ADBE: "Adobe",
  ADI: "Analog Devices",
  ADM: "Archer-Daniels-Midland",
  ADP: "Automatic Data Processing",
  ADSK: "Autodesk",
  AEE: "Ameren",
  AEP: "American Electric Power",
  AES: "AES Corporation",
  AFL: "Aflac",
  AIG: "American International Group",
  AIZ: "Assurant",
  AJG: "Arthur J. Gallagher",
  AKAM: "Akamai Technologies",
  ALB: "Albemarle",
  ALGN: "Align Technology",
  ALK: "Alaska Air Group",
  ALL: "Allstate",
  ALLE: "Allegion",
  AMAT: "Applied Materials",
  AMCR: "Amcor",
  AMD: "Advanced Micro Devices",
  AME: "AMETEK",
  AMGN: "Amgen",
  AMP: "Ameriprise Financial",
  AMT: "American Tower",
  AMZN: "Amazon",
  ANET: "Arista Networks",
  ANSS: "ANSYS",
  AON: "Aon",
  AOS: "A. O. Smith",
  APA: "APA Corporation",
  APD: "Air Products & Chemicals",
  APH: "Amphenol",
  APTV: "Aptiv",
  ARE: "Alexandria Real Estate",
  ATO: "Atmos Energy",
  ATVI: "Activision Blizzard",
  AVB: "AvalonBay Communities",
  AVGO: "Broadcom",
  AVY: "Avery Dennison",
  AWK: "American Water Works",
  AXP: "American Express",
  AZO: "AutoZone",
  BA: "Boeing",
  BAC: "Bank of America",
  BAX: "Baxter International",
  BBWI: "Bath & Body Works",
  BBY: "Best Buy",
  BDX: "Becton Dickinson",
  BEN: "Franklin Templeton",
  BF_B: "Brown-Forman",
  BG: "Bunge",
  BIIB: "Biogen",
  BIO: "Bio-Rad Laboratories",
  BK: "Bank of New York Mellon",
  BKNG: "Booking Holdings",
  BKR: "Baker Hughes",
  BLDR: "Builders FirstSource",
  BLK: "BlackRock",
  BMY: "Bristol-Myers Squibb",
  BR: "Broadridge Financial",
  BRK_B: "Berkshire Hathaway",
  BRO: "Brown & Brown",
  BSX: "Boston Scientific",
  BWA: "BorgWarner",
  BX: "Blackstone",
  BXP: "BXP Inc.",
  C: "Citigroup",
  CAG: "Conagra Brands",
  CAH: "Cardinal Health",
  CARR: "Carrier Global",
  CAT: "Caterpillar",
  CB: "Chubb",
  CBOE: "Cboe Global Markets",
  CBRE: "CBRE Group",
  CCI: "Crown Castle",
  CCL: "Carnival Corporation",
  CDAY: "Ceridian HCM",
  CDNS: "Cadence Design Systems",
  CDW: "CDW Corporation",
  CE: "Celanese",
  CEG: "Constellation Energy",
  CF: "CF Industries",
  CFG: "Citizens Financial Group",
  CHD: "Church & Dwight",
  CHRW: "C.H. Robinson",
  CHTR: "Charter Communications",
  CI: "Cigna Group",
  CINF: "Cincinnati Financial",
  CL: "Colgate-Palmolive",
  CLX: "Clorox",
  CMA: "Comerica",
  CMCSA: "Comcast",
  CME: "CME Group",
  CMG: "Chipotle Mexican Grill",
  CMI: "Cummins",
  CMS: "CMS Energy",
  CNC: "Centene",
  CNP: "CenterPoint Energy",
  COF: "Capital One Financial",
  COO: "CooperCompanies",
  COP: "ConocoPhillips",
  COR: "Cencora",
  COST: "Costco",
  CPB: "Campbell Soup",
  CPRT: "Copart",
  CPT: "Camden Property Trust",
  CRL: "Charles River Laboratories",
  CRM: "Salesforce",
  CRWD: "CrowdStrike",
  CSCO: "Cisco Systems",
  CSGP: "CoStar Group",
  CSX: "CSX Corporation",
  CTAS: "Cintas",
  CTLT: "Catalent",
  CTRA: "Coterra Energy",
  CTSH: "Cognizant Technology",
  CTVA: "Corteva",
  CVS: "CVS Health",
  CVX: "Chevron",
  CZR: "Caesars Entertainment",
  D: "Dominion Energy",
  DAL: "Delta Air Lines",
  DASH: "DoorDash",
  DD: "DuPont",
  DE: "Deere & Company",
  DECK: "Deckers Outdoor",
  DFS: "Discover Financial",
  DG: "Dollar General",
  DGX: "Quest Diagnostics",
  DHI: "D.R. Horton",
  DHR: "Danaher",
  DIS: "Walt Disney",
  DISH: "DISH Network",
  DLR: "Digital Realty",
  DLTR: "Dollar Tree",
  DOV: "Dover Corporation",
  DOW: "Dow Inc.",
  DPZ: "Domino's Pizza",
  DRI: "Darden Restaurants",
  DTE: "DTE Energy",
  DUK: "Duke Energy",
  DVA: "DaVita",
  DVN: "Devon Energy",
  DXCM: "DexCom",
  EA: "Electronic Arts",
  EBAY: "eBay",
  ECL: "Ecolab",
  ED: "Consolidated Edison",
  EFX: "Equifax",
  EIX: "Edison International",
  EL: "Estée Lauder",
  EMN: "Eastman Chemical",
  EMR: "Emerson Electric",
  ENPH: "Enphase Energy",
  EOG: "EOG Resources",
  EPAM: "EPAM Systems",
  EQIX: "Equinix",
  EQR: "Equity Residential",
  EQT: "EQT Corporation",
  ES: "Eversource Energy",
  ESS: "Essex Property Trust",
  ETN: "Eaton Corporation",
  ETR: "Entergy",
  ETSY: "Etsy",
  EVRG: "Evergy",
  EW: "Edwards Lifesciences",
  EXC: "Exelon",
  EXPD: "Expeditors International",
  EXPE: "Expedia Group",
  EXR: "Extra Space Storage",
  F: "Ford Motor",
  FANG: "Diamondback Energy",
  FAST: "Fastenal",
  FBHS: "Fortune Brands",
  FCX: "Freeport-McMoRan",
  FDS: "FactSet Research",
  FDX: "FedEx",
  FE: "FirstEnergy",
  FFIV: "F5 Networks",
  FI: "Fiserv",
  FICO: "Fair Isaac",
  FIS: "Fidelity National Information",
  FISV: "Fiserv",
  FITB: "Fifth Third Bancorp",
  FLT: "Fleetcor Technologies",
  FMC: "FMC Corporation",
  FOX: "Fox Corporation",
  FOXA: "Fox Corporation (Class A)",
  FRC: "First Republic Bank",
  FSLR: "First Solar",
  FTNT: "Fortinet",
  FTV: "Fortive",
  GD: "General Dynamics",
  GDDY: "GoDaddy",
  GE: "GE Aerospace",
  GEHC: "GE HealthCare",
  GEN: "Gen Digital",
  GILD: "Gilead Sciences",
  GIS: "General Mills",
  GL: "Globe Life",
  GLW: "Corning",
  GM: "General Motors",
  GNRC: "Generac Holdings",
  GOOG: "Alphabet (Class C)",
  GOOGL: "Alphabet",
  GPC: "Genuine Parts",
  GPN: "Global Payments",
  GRMN: "Garmin",
  GS: "Goldman Sachs",
  GWW: "W.W. Grainger",
  HAL: "Halliburton",
  HAS: "Hasbro",
  HBAN: "Huntington Bancshares",
  HCA: "HCA Healthcare",
  HD: "Home Depot",
  PEAK: "Healthpeak Properties",
  HES: "Hess Corporation",
  HIG: "Hartford Financial",
  HII: "Huntington Ingalls",
  HLT: "Hilton Worldwide",
  HOLX: "Hologic",
  HON: "Honeywell",
  HPE: "Hewlett Packard Enterprise",
  HPQ: "HP Inc.",
  HRL: "Hormel Foods",
  HSIC: "Henry Schein",
  HST: "Host Hotels & Resorts",
  HSY: "Hershey",
  HUBB: "Hubbell",
  HUM: "Humana",
  HWM: "Howmet Aerospace",
  IBM: "IBM",
  ICE: "Intercontinental Exchange",
  IDXX: "IDEXX Laboratories",
  IEX: "IDEX Corporation",
  IFF: "International Flavors & Fragrances",
  ILMN: "Illumina",
  INCY: "Incyte",
  INTC: "Intel",
  INTU: "Intuit",
  INVH: "Invitation Homes",
  IP: "International Paper",
  IPG: "Interpublic Group",
  IQV: "IQVIA Holdings",
  IR: "Ingersoll Rand",
  IRM: "Iron Mountain",
  ISRG: "Intuitive Surgical",
  IT: "Gartner",
  ITW: "Illinois Tool Works",
  IVZ: "Invesco",
  J: "Jacobs Solutions",
  JBHT: "J.B. Hunt Transport",
  JCI: "Johnson Controls",
  JKHY: "Jack Henry & Associates",
  JNJ: "Johnson & Johnson",
  JNPR: "Juniper Networks",
  JPM: "JPMorgan Chase",
  K: "Kellanova",
  KDP: "Keurig Dr Pepper",
  KEY: "KeyCorp",
  KEYS: "Keysight Technologies",
  KHC: "Kraft Heinz",
  KIM: "Kimco Realty",
  KLAC: "KLA Corporation",
  KMB: "Kimberly-Clark",
  KMI: "Kinder Morgan",
  KMX: "CarMax",
  KO: "Coca-Cola",
  KR: "Kroger",
  KVUE: "Kenvue",
  L: "Loews Corporation",
  LDOS: "Leidos Holdings",
  LEN: "Lennar",
  LH: "Labcorp",
  LHX: "L3Harris Technologies",
  LIN: "Linde",
  LKQ: "LKQ Corporation",
  LLY: "Eli Lilly",
  LMT: "Lockheed Martin",
  LNT: "Alliant Energy",
  LOW: "Lowe's",
  LRCX: "Lam Research",
  LULU: "Lululemon Athletica",
  LUV: "Southwest Airlines",
  LVS: "Las Vegas Sands",
  LW: "Lamb Weston",
  LYB: "LyondellBasell",
  LYV: "Live Nation Entertainment",
  MA: "Mastercard",
  MAA: "Mid-America Apartment",
  MAR: "Marriott International",
  MAS: "Masco",
  MCD: "McDonald's",
  MCHP: "Microchip Technology",
  MCK: "McKesson",
  MCO: "Moody's",
  MDLZ: "Mondelez International",
  MDT: "Medtronic",
  MET: "MetLife",
  META: "Meta Platforms",
  MGM: "MGM Resorts",
  MHK: "Mohawk Industries",
  MKC: "McCormick & Company",
  MKTX: "MarketAxess Holdings",
  MLM: "Martin Marietta Materials",
  MMC: "Marsh & McLennan",
  MMM: "3M",
  MNST: "Monster Beverage",
  MO: "Altria Group",
  MOH: "Molina Healthcare",
  MOS: "Mosaic Company",
  MPC: "Marathon Petroleum",
  MPWR: "Monolithic Power Systems",
  MRK: "Merck & Co.",
  MRNA: "Moderna",
  MRO: "Marathon Oil",
  MS: "Morgan Stanley",
  MSCI: "MSCI Inc.",
  MSFT: "Microsoft",
  MSI: "Motorola Solutions",
  MTB: "M&T Bank",
  MTCH: "Match Group",
  MTD: "Mettler-Toledo",
  MU: "Micron Technology",
  NCLH: "Norwegian Cruise Line",
  NDAQ: "Nasdaq Inc.",
  NDSN: "Nordson",
  NEE: "NextEra Energy",
  NEM: "Newmont",
  NFLX: "Netflix",
  NI: "NiSource",
  NKE: "Nike",
  NOC: "Northrop Grumman",
  NOW: "ServiceNow",
  NRG: "NRG Energy",
  NSC: "Norfolk Southern",
  NTAP: "NetApp",
  NTRS: "Northern Trust",
  NUE: "Nucor",
  NVDA: "NVIDIA",
  NVR: "NVR Inc.",
  NWL: "Newell Brands",
  NWS: "News Corp",
  NWSA: "News Corp (Class A)",
  NXPI: "NXP Semiconductors",
  O: "Realty Income",
  ODFL: "Old Dominion Freight Line",
  OKE: "ONEOK",
  OMC: "Omnicom Group",
  ON: "ON Semiconductor",
  ORCL: "Oracle",
  ORLY: "O'Reilly Automotive",
  OTIS: "Otis Worldwide",
  OXY: "Occidental Petroleum",
  PARA: "Paramount Global",
  PAYC: "Paycom Software",
  PAYX: "Paychex",
  PCAR: "PACCAR",
  PCG: "PG&E Corporation",
  PEAK_2: "Healthpeak Properties",
  PEG: "Public Service Enterprise",
  PEP: "PepsiCo",
  PFE: "Pfizer",
  PFG: "Principal Financial Group",
  PG: "Procter & Gamble",
  PGR: "Progressive",
  PH: "Parker-Hannifin",
  PHM: "PulteGroup",
  PKG: "Packaging Corp of America",
  PLD: "Prologis",
  PLTR: "Palantir Technologies",
  PM: "Philip Morris International",
  PNC: "PNC Financial Services",
  PNR: "Pentair",
  PNW: "Pinnacle West Capital",
  POOL: "Pool Corporation",
  PPG: "PPG Industries",
  PPL: "PPL Corporation",
  PRU: "Prudential Financial",
  PSA: "Public Storage",
  PSX: "Phillips 66",
  PTC: "PTC Inc.",
  PVH: "PVH Corp",
  PWR: "Quanta Services",
  PXD: "Pioneer Natural Resources",
  PYPL: "PayPal",
  QCOM: "Qualcomm",
  QRVO: "Qorvo",
  RCL: "Royal Caribbean",
  RE: "Everest Group",
  REG: "Regency Centers",
  REGN: "Regeneron Pharmaceuticals",
  RF: "Regions Financial",
  RHI: "Robert Half",
  RJF: "Raymond James Financial",
  RL: "Ralph Lauren",
  RMD: "ResMed",
  ROK: "Rockwell Automation",
  ROL: "Rollins",
  ROP: "Roper Technologies",
  ROST: "Ross Stores",
  RSG: "Republic Services",
  RTX: "RTX Corporation",
  RVTY: "Revvity",
  SBAC: "SBA Communications",
  SBNY: "Signature Bank",
  SBUX: "Starbucks",
  SCHW: "Charles Schwab",
  SEE: "Sealed Air",
  SHW: "Sherwin-Williams",
  SIVB: "SVB Financial Group",
  SJM: "J.M. Smucker",
  SLB: "Schlumberger",
  SNA: "Snap-on",
  SNPS: "Synopsys",
  SO: "Southern Company",
  SPG: "Simon Property Group",
  SPGI: "S&P Global",
  SRE: "Sempra Energy",
  STE: "STERIS",
  STLD: "Steel Dynamics",
  STT: "State Street",
  STX: "Seagate Technology",
  STZ: "Constellation Brands",
  SWK: "Stanley Black & Decker",
  SWKS: "Skyworks Solutions",
  SYF: "Synchrony Financial",
  SYK: "Stryker",
  SYY: "Sysco",
  T: "AT&T",
  TAP: "Molson Coors",
  TDG: "TransDigm Group",
  TDY: "Teledyne Technologies",
  TECH: "Bio-Techne",
  TEL: "TE Connectivity",
  TER: "Teradyne",
  TFC: "Truist Financial",
  TFX: "Teleflex",
  TGT: "Target",
  TJX: "TJX Companies",
  TMO: "Thermo Fisher Scientific",
  TMUS: "T-Mobile US",
  TPR: "Tapestry",
  TRGP: "Targa Resources",
  TRMB: "Trimble",
  TROW: "T. Rowe Price",
  TRV: "Travelers Companies",
  TSCO: "Tractor Supply",
  TSLA: "Tesla",
  TSN: "Tyson Foods",
  TT: "Trane Technologies",
  TTWO: "Take-Two Interactive",
  TXN: "Texas Instruments",
  TXT: "Textron",
  TYL: "Tyler Technologies",
  UAL: "United Airlines",
  UDR: "UDR Inc.",
  UHS: "Universal Health Services",
  ULTA: "Ulta Beauty",
  UNH: "UnitedHealth Group",
  UNP: "Union Pacific",
  UPS: "United Parcel Service",
  URI: "United Rentals",
  USB: "U.S. Bancorp",
  V: "Visa",
  VFC: "V.F. Corporation",
  VICI: "VICI Properties",
  VLO: "Valero Energy",
  VLTO: "Veralto",
  VMC: "Vulcan Materials",
  VRSK: "Verisk Analytics",
  VRSN: "VeriSign",
  VRTX: "Vertex Pharmaceuticals",
  VTR: "Ventas",
  VTRS: "Viatris",
  VZ: "Verizon",
  WAB: "Wabtec",
  WAT: "Waters Corporation",
  WBA: "Walgreens Boots Alliance",
  WBD: "Warner Bros. Discovery",
  WDC: "Western Digital",
  WEC: "WEC Energy Group",
  WELL: "Welltower",
  WFC: "Wells Fargo",
  WHR: "Whirlpool",
  WM: "Waste Management",
  WMB: "Williams Companies",
  WMT: "Walmart",
  WRB: "W.R. Berkley",
  WRK: "WestRock",
  WST: "West Pharmaceutical",
  WTW: "Willis Towers Watson",
  WY: "Weyerhaeuser",
  WYNN: "Wynn Resorts",
  XEL: "Xcel Energy",
  XOM: "Exxon Mobil",
  XRAY: "Dentsply Sirona",
  XYL: "Xylem",
  YUM: "Yum! Brands",
  ZBH: "Zimmer Biomet",
  ZBRA: "Zebra Technologies",
  ZTS: "Zoetis",

  // === Popular US ETFs ===
  SPY: "SPDR S&P 500 ETF",
  VOO: "Vanguard S&P 500 ETF",
  VTI: "Vanguard Total Stock Market ETF",
  QQQ: "Invesco QQQ Trust (Nasdaq 100)",
  IWM: "iShares Russell 2000 ETF",
  IVV: "iShares Core S&P 500 ETF",
  VGT: "Vanguard Information Technology ETF",
  VGK: "Vanguard FTSE Europe ETF",
  VXUS: "Vanguard Total International Stock ETF",
  VWO: "Vanguard FTSE Emerging Markets ETF",
  VEA: "Vanguard FTSE Developed Markets ETF",
  VNQ: "Vanguard Real Estate ETF",
  BND: "Vanguard Total Bond Market ETF",
  AGG: "iShares Core U.S. Aggregate Bond ETF",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  LQD: "iShares iBoxx Investment Grade Bond ETF",
  HYG: "iShares iBoxx High Yield Bond ETF",
  GLD: "SPDR Gold Shares",
  IAU: "iShares Gold Trust",
  SLV: "iShares Silver Trust",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  EFA: "iShares MSCI EAFE ETF",
  EEM: "iShares MSCI Emerging Markets ETF",
  XLF: "Financial Select Sector SPDR",
  XLK: "Technology Select Sector SPDR",
  XLE: "Energy Select Sector SPDR",
  XLV: "Health Care Select Sector SPDR",
  XLI: "Industrial Select Sector SPDR",
  XLP: "Consumer Staples Select Sector SPDR",
  XLY: "Consumer Discretionary Select Sector SPDR",
  XLU: "Utilities Select Sector SPDR",
  XLB: "Materials Select Sector SPDR",
  XLRE: "Real Estate Select Sector SPDR",
  XLC: "Communication Services Select Sector SPDR",
  ARKK: "ARK Innovation ETF",
  ARKG: "ARK Genomic Revolution ETF",
  ARKW: "ARK Next Generation Internet ETF",
  ARKF: "ARK Fintech Innovation ETF",
  SCHD: "Schwab U.S. Dividend Equity ETF",
  SCHX: "Schwab U.S. Large-Cap ETF",
  SCHA: "Schwab U.S. Small-Cap ETF",
  SCHF: "Schwab International Equity ETF",
  VIG: "Vanguard Dividend Appreciation ETF",
  VYM: "Vanguard High Dividend Yield ETF",
  VTIP: "Vanguard Short-Term Inflation-Protected ETF",
  VCIT: "Vanguard Intermediate-Term Corporate Bond ETF",
  VCSH: "Vanguard Short-Term Corporate Bond ETF",
  VGSH: "Vanguard Short-Term Treasury ETF",
  VGIT: "Vanguard Intermediate-Term Treasury ETF",
  VGLT: "Vanguard Long-Term Treasury ETF",
  VTV: "Vanguard Value ETF",
  VUG: "Vanguard Growth ETF",
  VO: "Vanguard Mid-Cap ETF",
  VB: "Vanguard Small-Cap ETF",
  ITOT: "iShares Core S&P Total U.S. Stock Market ETF",
  IXUS: "iShares Core MSCI Total International Stock ETF",
  IJR: "iShares Core S&P Small-Cap ETF",
  IJH: "iShares Core S&P Mid-Cap ETF",
  IWF: "iShares Russell 1000 Growth ETF",
  IWD: "iShares Russell 1000 Value ETF",
  IWB: "iShares Russell 1000 ETF",
  IEMG: "iShares Core MSCI Emerging Markets ETF",
  IEFA: "iShares Core MSCI EAFE ETF",
  QUAL: "iShares MSCI USA Quality Factor ETF",
  MTUM: "iShares MSCI USA Momentum Factor ETF",
  USMV: "iShares MSCI USA Min Vol Factor ETF",
  HDV: "iShares Core High Dividend ETF",
  DVY: "iShares Select Dividend ETF",
  RSP: "Invesco S&P 500 Equal Weight ETF",
  TQQQ: "ProShares UltraPro QQQ",
  SQQQ: "ProShares UltraPro Short QQQ",
  SOXX: "iShares Semiconductor ETF",
  SMH: "VanEck Semiconductor ETF",
  KWEB: "KraneShares CSI China Internet ETF",
  MCHI: "iShares MSCI China ETF",
  FXI: "iShares China Large-Cap ETF",
  INDA: "iShares MSCI India ETF",
  EWJ: "iShares MSCI Japan ETF",
  EWZ: "iShares MSCI Brazil ETF",
  EWG: "iShares MSCI Germany ETF",
  EWU: "iShares MSCI United Kingdom ETF",
  JEPI: "JPMorgan Equity Premium Income ETF",
  JEPQ: "JPMorgan Nasdaq Equity Premium Income ETF",
  BSV: "Vanguard Short-Term Bond ETF",
  BIV: "Vanguard Intermediate-Term Bond ETF",
  BLV: "Vanguard Long-Term Bond ETF",
  BNDX: "Vanguard Total International Bond ETF",
  EMB: "iShares J.P. Morgan USD Emerging Markets Bond ETF",
  TIP: "iShares TIPS Bond ETF",
  SHY: "iShares 1-3 Year Treasury Bond ETF",
  IEF: "iShares 7-10 Year Treasury Bond ETF",
  MUB: "iShares National Muni Bond ETF",
  GOVT: "iShares U.S. Treasury Bond ETF",

  // === Vanguard Mutual Funds ===
  VFIAX: "Vanguard 500 Index Fund Admiral",
  VTSAX: "Vanguard Total Stock Market Index Admiral",
  VBTLX: "Vanguard Total Bond Market Index Admiral",
  VTIAX: "Vanguard Total International Stock Index Admiral",
  VWENX: "Vanguard Wellington Fund Admiral",
  VWNEX: "Vanguard Windsor Fund Admiral",
  VEXAX: "Vanguard Extended Market Index Admiral",
  VIGAX: "Vanguard Growth Index Admiral",
  VVIAX: "Vanguard Value Index Admiral",
  VSIAX: "Vanguard Small-Cap Value Index Admiral",
  VSMAX: "Vanguard Small-Cap Index Admiral",
  VMFXX: "Vanguard Federal Money Market Fund",
  VMMXX: "Vanguard Prime Money Market Fund",

  // === Fidelity Mutual Funds ===
  FXAIX: "Fidelity 500 Index Fund",
  FSKAX: "Fidelity Total Market Index Fund",
  FTIHX: "Fidelity Total International Index Fund",
  FZROX: "Fidelity ZERO Total Market Index Fund",
  FZILX: "Fidelity ZERO International Index Fund",
  FNILX: "Fidelity ZERO Large Cap Index Fund",
  FXNAX: "Fidelity U.S. Bond Index Fund",
  FCNTX: "Fidelity Contrafund",

  // === Canadian Stocks ===
  "RY.TO": "Royal Bank of Canada",
  "TD.TO": "Toronto-Dominion Bank",
  "BNS.TO": "Bank of Nova Scotia",
  "BMO.TO": "Bank of Montreal",
  "CM.TO": "Canadian Imperial Bank of Commerce",
  "ENB.TO": "Enbridge",
  "CNR.TO": "Canadian National Railway",
  "CP.TO": "Canadian Pacific Kansas City",
  "SU.TO": "Suncor Energy",
  "CNQ.TO": "Canadian Natural Resources",
  "TRP.TO": "TC Energy",
  "MFC.TO": "Manulife Financial",
  "SLF.TO": "Sun Life Financial",
  "BCE.TO": "BCE Inc.",
  "T.TO": "TELUS",
  "ABX.TO": "Barrick Gold",
  "FNV.TO": "Franco-Nevada",
  "WPM.TO": "Wheaton Precious Metals",
  "ATD.TO": "Alimentation Couche-Tard",
  "CSU.TO": "Constellation Software",
  "SHOP.TO": "Shopify",
  "BAM.TO": "Brookfield Asset Management",
  "BN.TO": "Brookfield Corporation",
  "NTR.TO": "Nutrien",
  "GIB_A.TO": "CGI Inc.",
  "MG.TO": "Magna International",
  "L.TO": "Loblaw Companies",
  "WCN.TO": "Waste Connections",
  "DOL.TO": "Dollarama",
  "QSR.TO": "Restaurant Brands International",

  // === Canadian ETFs ===
  "XIU.TO": "iShares S&P/TSX 60 Index ETF",
  XIU: "iShares S&P/TSX 60 Index ETF",
  "XIC.TO": "iShares Core S&P/TSX Capped Composite Index ETF",
  XIC: "iShares Core S&P/TSX Capped Composite Index ETF",
  "VFV.TO": "Vanguard S&P 500 Index ETF (CAD)",
  VFV: "Vanguard S&P 500 Index ETF (CAD)",
  "VCN.TO": "Vanguard FTSE Canada All Cap Index ETF",
  VCN: "Vanguard FTSE Canada All Cap Index ETF",
  "ZSP.TO": "BMO S&P 500 Index ETF",
  ZSP: "BMO S&P 500 Index ETF",
  "XEI.TO": "iShares S&P/TSX Composite High Dividend Index ETF",
  XEI: "iShares S&P/TSX Composite High Dividend Index ETF",
  "VEQT.TO": "Vanguard All-Equity ETF Portfolio",
  VEQT: "Vanguard All-Equity ETF Portfolio",
  "VGRO.TO": "Vanguard Growth ETF Portfolio",
  VGRO: "Vanguard Growth ETF Portfolio",
  "VBAL.TO": "Vanguard Balanced ETF Portfolio",
  VBAL: "Vanguard Balanced ETF Portfolio",
  "XEQT.TO": "iShares Core Equity ETF Portfolio",
  XEQT: "iShares Core Equity ETF Portfolio",
  "XGRO.TO": "iShares Core Growth ETF Portfolio",
  XGRO: "iShares Core Growth ETF Portfolio",
  "XBAL.TO": "iShares Core Balanced ETF Portfolio",
  XBAL: "iShares Core Balanced ETF Portfolio",
  "ZAG.TO": "BMO Aggregate Bond Index ETF",
  ZAG: "BMO Aggregate Bond Index ETF",

  // === Other Popular Tickers ===
  COIN: "Coinbase Global",
  HOOD: "Robinhood Markets",
  RBLX: "Roblox",
  SNOW: "Snowflake",
  DDOG: "Datadog",
  NET: "Cloudflare",
  ZS: "Zscaler",
  PANW: "Palo Alto Networks",
  SHOP: "Shopify",
  SQ: "Block Inc.",
  SPOT: "Spotify",
  UBER: "Uber Technologies",
  LYFT: "Lyft",
  SNAP: "Snap Inc.",
  PINS: "Pinterest",
  ROKU: "Roku",
  U: "Unity Software",
  TTD: "The Trade Desk",
  MELI: "MercadoLibre",
  SE: "Sea Limited",
  BABA: "Alibaba Group",
  JD: "JD.com",
  PDD: "PDD Holdings (Temu)",
  NIO: "NIO Inc.",
  LI: "Li Auto",
  XPEV: "XPeng",
  RIVN: "Rivian Automotive",
  LCID: "Lucid Group",
  SOFI: "SoFi Technologies",
  PLTR_2: "Palantir Technologies",
  PATH: "UiPath",
  AI: "C3.ai",
  SMCI: "Super Micro Computer",
  ARM: "Arm Holdings",
  CELH: "Celsius Holdings",
  DUOL: "Duolingo",
  ABNB_2: "Airbnb",
  CRSP: "CRISPR Therapeutics",
  EDIT: "Editas Medicine",
  NTLA: "Intellia Therapeutics",
  BEAM: "Beam Therapeutics",
  BTC: "Bitcoin",
  ETH: "Ethereum",
  GBTC: "Grayscale Bitcoin Trust",
  ETHE: "Grayscale Ethereum Trust",
  IBIT: "iShares Bitcoin Trust ETF",
  FBTC: "Fidelity Wise Origin Bitcoin Fund",
  BITB: "Bitwise Bitcoin ETF",
  MSTR: "MicroStrategy",
};

// Remove duplicate suffixed entries (PLTR_2, ABNB_2, PEAK_2)
delete TICKER_NAMES["PLTR_2"];
delete TICKER_NAMES["ABNB_2"];
delete TICKER_NAMES["PEAK_2"];

/** Synchronous lookup of a ticker name from the static map */
export function getTickerName(ticker: string): string | undefined {
  if (!ticker) return undefined;
  const upper = ticker.toUpperCase().trim();
  return TICKER_NAMES[upper] ?? TICKER_NAMES[ticker.trim()];
}

// Module-level cache for resolved ticker names
const resolvedCache = new Map<string, string | undefined>();

/**
 * Async lookup for tickers not in the static map.
 * Attempts a free finance API call, caches the result.
 * Returns undefined if the lookup fails (graceful fallback).
 */
export async function resolveTickerName(
  ticker: string
): Promise<string | undefined> {
  if (!ticker) return undefined;
  const upper = ticker.toUpperCase().trim();

  // Check static map first
  const staticName = getTickerName(upper);
  if (staticName) return staticName;

  // Check cache
  if (resolvedCache.has(upper)) return resolvedCache.get(upper);

  try {
    // Use Yahoo Finance v8 auto-complete endpoint (free, no API key)
    const res = await fetch(
      `https://query2.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(upper)}&quotesCount=1&newsCount=0`,
      { signal: AbortSignal.timeout(5000) }
    );
    if (!res.ok) {
      resolvedCache.set(upper, undefined);
      return undefined;
    }
    const data = await res.json();
    const quote = data?.quotes?.[0];
    if (quote && (quote.shortname || quote.longname)) {
      const name = (quote.shortname || quote.longname) as string;
      resolvedCache.set(upper, name);
      return name;
    }
    resolvedCache.set(upper, undefined);
    return undefined;
  } catch {
    resolvedCache.set(upper, undefined);
    return undefined;
  }
}

/** Clear the resolved cache (useful for testing) */
export function clearResolvedCache(): void {
  resolvedCache.clear();
}

/** Get the number of entries in the static map (useful for testing) */
export function getStaticMapSize(): number {
  return Object.keys(TICKER_NAMES).length;
}
